# Generated by Django 2.2.2 on 2020-06-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritcle',
            new_name='Article',
        ),
    ]
